Added Gradle wrapper validation to CI workflow
This way we can eliminate dedicated workflow and make our CI setup simpler.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,37 +22,40 @@ jobs:
     # All build steps
     steps:
 
-    - name: 1. Check out code
-      uses: actions/checkout@v2 # https://github.com/actions/checkout
-      with:
-        fetch-depth: '0' # https://github.com/shipkit/shipkit-changelog#fetch-depth-on-ci
+      - name: 1. Check out code
+        uses: actions/checkout@v2 # https://github.com/actions/checkout
+        with:
+          fetch-depth: '0' # https://github.com/shipkit/shipkit-changelog#fetch-depth-on-ci
 
-    - name: 2. Set up Java ${{ matrix.java }}
-      uses: actions/setup-java@v1
-      with:
-        java-version: ${{ matrix.java }}
+      - name: 2. Set up Java ${{ matrix.java }}
+        uses: actions/setup-java@v1
+        with:
+          java-version: ${{ matrix.java }}
 
-    # TODO: add step for gradle wrapper validation and remove the other workflow
+      - name: 3. Validate Gradle wrapper
+        # Run just once, attached to one matrix job
+        if: matrix.java == 8 && matrix.mock-maker == 'mock-maker-default'
+        uses: gradle/wrapper-validation-action@v1 # https://github.com/gradle/wrapper-validation-action
 
-    - name: 3. Build and check reproducibility of artifacts (single job only)
-      # Run on a single job, with the version of java used for releases
-      if: matrix.java == 8 && matrix.mock-maker == 'mock-maker-default'
-      run: ./check_reproducibility.sh
+      - name: 4. Build and check reproducibility of artifacts (single job only)
+        # Run on one matrix job, with the version of java used for releases
+        if: matrix.java == 8 && matrix.mock-maker == 'mock-maker-default'
+        run: ./check_reproducibility.sh
 
-    - name: 4. Spotless check (single job only). Run './gradlew spotlessApply' locally if this job fails.
-      # Run on a single job, with java version compatible with spotless
-      if: matrix.java == 11 && matrix.mock-maker == 'mock-maker-default'
-      run: ./gradlew spotlessCheck
+      - name: 5. Spotless check (single job only). Run './gradlew spotlessApply' locally if this job fails.
+        # Run on one matrix job, with java version compatible with spotless
+        if: matrix.java == 11 && matrix.mock-maker == 'mock-maker-default'
+        run: ./gradlew spotlessCheck
 
-    - name: 5. Build on Java ${{ matrix.java }} with ${{ matrix.mock-maker }}
-      run: ./gradlew build bintrayUpload idea --scan -PbintrayDryRun
-      env:
-        MOCK_MAKER: ${{ matrix.mock-maker }}
+      - name: 6. Build on Java ${{ matrix.java }} with ${{ matrix.mock-maker }}
+        run: ./gradlew build bintrayUpload idea --scan -PbintrayDryRun
+        env:
+          MOCK_MAKER: ${{ matrix.mock-maker }}
 
-    - name: 6. Upload coverage report
-      run: |
-        ./gradlew coverageReport -s --scan && cp build/reports/jacoco/mockitoCoverage/mockitoCoverage.xml jacoco.xml || echo "Code coverage failed"
-        bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
+      - name: 7. Upload coverage report
+        run: |
+          ./gradlew coverageReport -s --scan && cp build/reports/jacoco/mockitoCoverage/mockitoCoverage.xml jacoco.xml || echo "Code coverage failed"
+          bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
 
   # 
   # Release job, only for pushes to the main branch
